version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "ignaigna"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "ignaigna"
